#!/usr/bin/env python3
"""Embed The Gate Is Open! JSON content into a C++ header for the firmware.

The portable engine consumes the SAME JSON content format used on desktop; this
just makes the bytes available without a filesystem. Run this whenever the Gate
content changes:

    python3 embed_content.py [GATE_REPO_DIR]

Default GATE_REPO_DIR is ~/Downloads/the-gate-is-open. Output is written to
../GateContent.generated.h (i.e. src/activities/gate/GateContent.generated.h).

The story JSON is validated by the engine at runtime; this tool only copies
bytes verbatim into a raw string literal, so no narrative logic is hardcoded.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "GateContent.generated.h"))
DELIM = "GATEJSON"  # raw-string delimiter; JSON never contains )GATEJSON"


def raw(s: str) -> str:
    if (")" + DELIM + '"') in s:
        raise SystemExit("content collides with raw-string delimiter; change DELIM")
    return 'R"' + DELIM + "(" + s + ")" + DELIM + '"'


def main() -> None:
    repo = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/Downloads/the-gate-is-open")
    content = os.path.join(repo, "content")
    files = {
        "kGateCharactersJson": os.path.join(content, "characters.json"),
        "kGateRelationshipsJson": os.path.join(content, "relationships.json"),
        "kGateChachaStoryJson": os.path.join(content, "stories", "chacha-door-open.json"),
    }
    parts = [
        "// GENERATED by src/activities/gate/tools/embed_content.py -- do not edit by hand.",
        "// Source: the-gate-is-open/content/*.json (verbatim; validated at runtime).",
        "#pragma once",
        "",
        "namespace gate_content {",
        "",
    ]
    for name, path in files.items():
        with open(path, "r", encoding="utf-8") as f:
            data = f.read()
        parts.append(f"inline constexpr char {name}[] = {raw(data)};")
        parts.append("")
    parts.append("}  // namespace gate_content")
    parts.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
