// GENERATED by src/activities/gate/tools/embed_content.py -- do not edit by hand.
// Source: the-gate-is-open/content/*.json (verbatim; validated at runtime).
#pragma once

namespace gate_content {

inline constexpr char kGateCharactersJson[] = R"GATEJSON([
  {
    "id": "chacha",
    "name": "CHACHA",
    "species": "chihuahua",
    "short_desc": "Fearless chihuahua. Freedom detected -> maximum velocity.",
    "portrait": "chacha_portrait",
    "playable": true,
    "intro": "CHACHA is small, extremely confident, and already eyeing the far wall.\n\nWhen a gap appears, she does not deliberate. She accelerates.",
    "attributes": { "energy": 3, "confidence": 3, "mood": 1 }
  },
  {
    "id": "shadow",
    "name": "SHADOW",
    "species": "husky-aspin",
    "short_desc": "Goofball husky-aspin. Barks first, thinks maybe later.",
    "portrait": "shadow_portrait",
    "playable": true,
    "intro": "SHADOW is large, loud, and easily delighted.\n\n(Playable slice coming soon -- for now, watch him react.)",
    "attributes": { "energy": 3, "confidence": 2, "mood": 2 }
  },
  {
    "id": "chico",
    "name": "CHICO",
    "species": "cat",
    "short_desc": "Black/grey cat who always wants inside.",
    "portrait": "chico_portrait",
    "playable": true,
    "intro": "CHICO watches from the ledge. He is patient. He is calculating.\n\n(Playable slice coming soon -- for now, he schemes.)",
    "attributes": { "energy": 2, "confidence": 2, "mood": 1 }
  },
  {
    "id": "kali",
    "name": "Kali",
    "species": "labrador",
    "short_desc": "Spoiled black Labrador. Joins any commotion.",
    "portrait": "kali_portrait",
    "playable": false,
    "intro": "",
    "attributes": { "energy": 3 }
  },
  {
    "id": "puppy",
    "name": "Puppy",
    "species": "aspin",
    "short_desc": "The household 'big dog'. Taunts Shadow.",
    "portrait": "puppy_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  },
  {
    "id": "leeg",
    "name": "Leeg",
    "species": "aspin",
    "short_desc": "Long-necked aspin. Scared of nearly everything.",
    "portrait": "leeg_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  },
  {
    "id": "itim",
    "name": "Itim",
    "species": "aspin",
    "short_desc": "Eldest female aspin. Watches. Judges.",
    "portrait": "itim_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  },
  {
    "id": "nami",
    "name": "Nami",
    "species": "aspin",
    "short_desc": "Neighbor's aspin. Three puppies. Eyes Chico's food.",
    "portrait": "nami_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  }
]
)GATEJSON";

inline constexpr char kGateRelationshipsJson[] = R"GATEJSON([
  { "from": "shadow", "to": "puppy", "kind": "hostile", "intensity": 3 },
  { "from": "puppy", "to": "shadow", "kind": "hostile", "intensity": 3 },
  { "from": "kali", "to": "itim", "kind": "hostile", "intensity": 2 },
  { "from": "itim", "to": "kali", "kind": "hostile", "intensity": 2 },
  { "from": "puppy", "to": "itim", "kind": "deferential", "intensity": 2 },
  { "from": "nami", "to": "chico", "kind": "food", "intensity": 2 },
  { "from": "chico", "to": "nami", "kind": "food", "intensity": 2 }
]
)GATEJSON";

inline constexpr char kGateChachaStoryJson[] = R"GATEJSON({
  "id": "chacha-door-open-01",
  "title": "The Gate Is Open!",
  "character": "chacha",
  "start": "open_door",
  "actors_default": ["chacha"],
  "_note": "Canonical V1 Chacha episode STRUCTURE. All text is structural placeholder in [brackets]; final prose is written later. Reconverging-diamond: Fork1(route) -> escalate -> Fork2(escalation) -> chaos beat -> winded -> Fork3(final act) -> 5 resolutions -> shared epilogue -> Shadow stinger.",
  "nodes": {

    "open_door": {
      "text": "[The front door of Home is open.]\n[Nobody has noticed yet.]\n[Chacha has noticed.]",
      "art": "scene:open_front_door",
      "actors": ["chacha"],
      "choices": [
        {
          "text": "Run to the Far End",
          "next": "far_end",
          "effects": [
            { "op": "set", "key": "flags.route", "value": "far_end" },
            { "op": "inc", "key": "char.chacha.confidence", "by": 1 }
          ]
        },
        {
          "text": "Cut through the Covered Yard",
          "next": "covered_yard",
          "effects": [
            { "op": "set", "key": "flags.route", "value": "covered_yard" },
            { "op": "inc", "key": "flags.ruckus", "by": 1 }
          ]
        },
        {
          "text": "Loop toward the Gate Side",
          "next": "gate_side",
          "effects": [
            { "op": "set", "key": "flags.route", "value": "gate_side" }
          ]
        }
      ]
    },

    "far_end": {
      "text": "[Chacha bolts for the weedy Far End, tail high. This is the frontier.]",
      "art": "scene:far_end",
      "actors": ["chacha", "nami"],
      "reactions": [
        {
          "id": "nami_notices",
          "effects": [ { "op": "set", "key": "flags.nami_noticed", "value": true } ],
          "text": "[Nami lifts her head. Her puppies stir.]"
        },
        {
          "id": "puppies_stir",
          "chance": 60,
          "effects": [ { "op": "set", "key": "flags.puppies_up", "value": true } ]
        }
      ],
      "auto": "escalate"
    },

    "covered_yard": {
      "text": "[Chacha barrels through the Covered Yard, scattering what dignity the household had left.]",
      "art": "scene:covered_yard",
      "actors": ["chacha", "puppy", "itim", "leeg"],
      "reactions": [
        {
          "id": "leeg_retreats",
          "effects": [ { "op": "set", "key": "flags.leeg_hiding", "value": true } ],
          "text": "[Leeg bolts behind the water drum.]"
        },
        {
          "id": "puppy_notices",
          "effects": [ { "op": "set", "key": "flags.puppy_alert", "value": true } ]
        },
        {
          "id": "itim_watches",
          "effects": [ { "op": "set", "key": "flags.itim_watching", "value": true } ]
        }
      ],
      "auto": "escalate"
    },

    "gate_side": {
      "text": "[Chacha loops toward the shed and the big closed main gate. No way out — just laps. The front door of Home stands wide behind her.]",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "chico_opportunity",
          "effects": [ { "op": "set", "key": "flags.chico_inside", "value": true } ]
        }
      ],
      "auto": "escalate"
    },

    "escalate": {
      "text": "[The compound is noticing her now.]",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "human_calls_early",
          "text": "[Human: “Chacha! Get back here!” She does not respond.]"
        }
      ],
      "choices": [
        {
          "text": "Keep going",
          "next": "keep_going",
          "effects": [
            { "op": "inc", "key": "char.chacha.confidence", "by": 1 },
            { "op": "dec", "key": "char.chacha.energy", "by": 1 }
          ]
        },
        {
          "text": "Boomerang back toward Home",
          "next": "boomerang",
          "effects": [
            { "op": "inc", "key": "flags.boomerang_count", "by": 1 },
            { "op": "dec", "key": "char.chacha.energy", "by": 1 }
          ]
        },
        {
          "text": "Buzz the other dogs",
          "next": "buzz_dogs",
          "effects": [
            { "op": "inc", "key": "flags.ruckus", "by": 2 },
            { "op": "dec", "key": "char.chacha.energy", "by": 2 }
          ]
        }
      ]
    },

    "keep_going": {
      "text": "[Chacha commits, pushing deeper. This is HER adventure and she is enormous.]",
      "art": "portrait:chacha:chaos",
      "actors": ["chacha", "kali"],
      "reactions": [
        {
          "id": "kali_interested",
          "effects": [ { "op": "set", "key": "flags.kali_joined", "value": true } ],
          "text": "[Kali strains at the door, desperate to join.]"
        },
        {
          "id": "puppies_follow",
          "when": [ { "key": "flags.route", "op": "eq", "value": "far_end" } ],
          "effects": [ { "op": "set", "key": "flags.puppies_following", "value": true } ]
        }
      ],
      "auto": "chaos"
    },

    "boomerang": {
      "text": "[Chacha wheels around and rockets back toward Home, ears flat, delighted with herself.]",
      "art": "scene:chacha_boomerang",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "chico_slips",
          "effects": [ { "op": "set", "key": "flags.chico_inside", "value": true } ]
        }
      ],
      "auto": "chaos"
    },

    "buzz_dogs": {
      "text": "[Chacha gets right up in the big dogs’ faces, absolutely certain she outweighs them.]",
      "art": "portrait:chacha:chaos",
      "actors": ["chacha", "puppy", "itim", "leeg"],
      "reactions": [
        {
          "id": "puppy_squares_up",
          "effects": [ { "op": "set", "key": "flags.puppy_alert", "value": true } ],
          "text": "[Puppy squares up, entirely unimpressed.]"
        },
        {
          "id": "itim_look",
          "effects": [ { "op": "set", "key": "flags.itim_watching", "value": true } ]
        }
      ],
      "auto": "chaos"
    },

    "chaos": {
      "text": "[THE COMPOUND ERUPTS.]",
      "beat": true,
      "actors": ["chacha", "kali", "shadow", "puppy", "nami", "leeg"],
      "reactions": [
        {
          "id": "shadow_barks",
          "effects": [ { "op": "set", "key": "flags.shadow_barking", "value": true } ],
          "text": "[Shadow, from his crate: BORK BORK BORK.]"
        },
        {
          "id": "chico_sneaks",
          "when": [ { "key": "flags.chico_inside", "op": "set" } ],
          "effects": [ { "op": "set", "key": "flags.chico_inside", "value": true } ]
        }
      ],
      "auto": "winded"
    },

    "winded": {
      "text": "[Chacha is panting now. Little sides going like bellows.]\n[The human has stopped chasing — just waiting for the battery to run flat.]",
      "art": "portrait:chacha:wary",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "human_waits",
          "text": "[Human, arms crossed: “I can do this all day. You can’t.”]"
        }
      ],
      "auto": "final_fork"
    },

    "final_fork": {
      "text": "[The last of the battery. How does Chacha spend it?]",
      "actors": ["chacha"],
      "choices": [
        {
          "text": "One more lap",
          "next": "res_velocity",
          "when": [
            { "key": "char.chacha.confidence", "op": "gte", "value": 5 },
            { "key": "char.chacha.energy", "op": "gte", "value": 1 }
          ]
        },
        {
          "text": "Boomerang home one more time",
          "next": "res_boomerang",
          "when": [ { "key": "flags.boomerang_count", "op": "gte", "value": 1 } ]
        },
        {
          "text": "One last act of tiny menace",
          "next": "res_menace",
          "when": [ { "key": "flags.ruckus", "op": "gte", "value": 2 } ]
        },
        {
          "text": "Trot home like it was the plan",
          "next": "res_dignity",
          "when": [ { "key": "char.chacha.energy", "op": "gte", "value": 2 } ]
        },
        {
          "text": "Flop down, out of juice",
          "next": "res_battery"
        }
      ]
    },

    "res_velocity": {
      "text": "[Chacha executes one final, absurdly committed circuit of the whole compound. Glorious. Pointless. Then the tank hits empty.]",
      "art": "portrait:chacha:chaos",
      "actors": ["chacha"],
      "reactions": [
        { "id": "mark_velocity", "effects": [ { "op": "set", "key": "flags.ending", "value": "maximum_velocity" } ] }
      ],
      "auto": "epilogue_pickup"
    },

    "res_boomerang": {
      "text": "[Out and back, out and back — the crazed boomerang runs its full course until Chacha wobbles to a halt near Home.]",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "mark_boomerang",
          "effects": [
            { "op": "set", "key": "flags.ending", "value": "crazed_boomerang" },
            { "op": "inc", "key": "flags.boomerang_count", "by": 1 }
          ]
        }
      ],
      "auto": "epilogue_pickup"
    },

    "res_menace": {
      "text": "[Chacha starts a diplomatic incident wildly disproportionate to her size. Nobody is hurt. Everybody is offended.]",
      "actors": ["chacha", "itim", "puppy"],
      "reactions": [
        { "id": "mark_menace", "effects": [ { "op": "set", "key": "flags.ending", "value": "tiny_menace" } ] },
        {
          "id": "itim_the_look",
          "when": [ { "key": "flags.itim_watching", "op": "set" } ],
          "text": "[Itim gives her The Look. Even Chacha briefly reconsiders her whole approach.]"
        }
      ],
      "auto": "epilogue_pickup"
    },

    "res_dignity": {
      "text": "[Chacha trots home with her chin up, as if this had all, obviously, been the plan from the start.]",
      "actors": ["chacha"],
      "reactions": [
        { "id": "mark_dignity", "effects": [ { "op": "set", "key": "flags.ending", "value": "i_meant_to" } ] }
      ],
      "auto": "epilogue_pickup"
    },

    "res_battery": {
      "text": "[Chacha simply runs out of juice. She stops in the middle of the compound, panting, blinking, thoroughly done.]",
      "art": "portrait:chacha:wary",
      "actors": ["chacha"],
      "reactions": [
        { "id": "mark_battery", "effects": [ { "op": "set", "key": "flags.ending", "value": "battery_low" } ] }
      ],
      "auto": "epilogue_pickup"
    },

    "epilogue_pickup": {
      "text": "[The human walks over, still scolding, and scoops up the exhausted little terror. She is far too tired to resist.]",
      "art": "portrait:chacha:wary",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "chico_surfaces",
          "when": [ { "key": "flags.chico_inside", "op": "set" } ],
          "text": "[Somehow, Chico is already inside, pretending he has always lived here.]"
        }
      ],
      "auto": "epilogue_crate"
    },

    "epilogue_crate": {
      "text": "[Near the crate the human looks at the panting menace, laughs, and kisses her on the forehead.]\n[In she goes. The latch clicks shut.]",
      "actors": ["chacha"],
      "auto": "epilogue_sleep"
    },

    "epilogue_sleep": {
      "text": "[Chacha is asleep before the human even straightens up.]",
      "actors": ["chacha"],
      "auto": "stinger_wake"
    },

    "stinger_wake": {
      "text": "[A crash. Somewhere. Chacha’s eyes snap open — spent, and instantly, completely ready for the next emergency.]",
      "actors": ["chacha"],
      "auto": "stinger_beat"
    },

    "stinger_beat": {
      "text": "[SHADOW IS OUT.]",
      "beat": true,
      "actors": ["shadow"],
      "auto": "prompt_shadow"
    },

    "prompt_shadow": {
      "text": "[PLAY AS SHADOW?]",
      "actors": ["shadow"],
      "choices": [
        { "text": "Play as Shadow", "next": "end_shadow_next" },
        { "text": "Not now", "next": "end_home" }
      ]
    },

    "end_shadow_next": {
      "text": "[Shadow’s episode isn’t built yet — for now, back to Home.]\n[V1 loop: Chacha → Shadow → Chico.]",
      "ending": true,
      "ending_id": "shadow_next"
    },

    "end_home": {
      "text": "[Home. The compound settles. For now.]",
      "ending": true,
      "ending_id": "home"
    }
  }
}
)GATEJSON";

}  // namespace gate_content
