// GENERATED by src/activities/gate/tools/embed_content.py -- do not edit by hand.
// Source: the-gate-is-open/content/*.json (verbatim; validated at runtime).
#pragma once

namespace gate_content {

inline constexpr char kGateCharactersJson[] = R"GATEJSON([
  {
    "id": "chacha",
    "name": "CHACHA",
    "species": "chihuahua",
    "short_desc": "Fearless chihuahua. Freedom detected -> maximum velocity.",
    "portrait": "chacha_portrait",
    "playable": true,
    "intro": "CHACHA is small, extremely confident, and already eyeing the far wall.\n\nWhen a gap appears, she does not deliberate. She accelerates.",
    "attributes": { "energy": 3, "confidence": 3, "mood": 1 }
  },
  {
    "id": "shadow",
    "name": "SHADOW",
    "species": "husky-aspin",
    "short_desc": "Goofball husky-aspin. Barks first, thinks maybe later.",
    "portrait": "shadow_portrait",
    "playable": true,
    "intro": "SHADOW is large, loud, and easily delighted.\n\n(Playable slice coming soon -- for now, watch him react.)",
    "attributes": { "energy": 3, "confidence": 2, "mood": 2 }
  },
  {
    "id": "chico",
    "name": "CHICO",
    "species": "cat",
    "short_desc": "Black/grey cat who always wants inside.",
    "portrait": "chico_portrait",
    "playable": true,
    "intro": "CHICO watches from the ledge. He is patient. He is calculating.\n\n(Playable slice coming soon -- for now, he schemes.)",
    "attributes": { "energy": 2, "confidence": 2, "mood": 1 }
  },
  {
    "id": "kali",
    "name": "Kali",
    "species": "labrador",
    "short_desc": "Spoiled black Labrador. Joins any commotion.",
    "portrait": "kali_portrait",
    "playable": false,
    "intro": "",
    "attributes": { "energy": 3 }
  },
  {
    "id": "puppy",
    "name": "Puppy",
    "species": "aspin",
    "short_desc": "The household 'big dog'. Taunts Shadow.",
    "portrait": "puppy_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  },
  {
    "id": "leeg",
    "name": "Leeg",
    "species": "aspin",
    "short_desc": "Long-necked aspin. Scared of nearly everything.",
    "portrait": "leeg_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  },
  {
    "id": "itim",
    "name": "Itim",
    "species": "aspin",
    "short_desc": "Eldest female aspin. Watches. Judges.",
    "portrait": "itim_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  },
  {
    "id": "nami",
    "name": "Nami",
    "species": "aspin",
    "short_desc": "Neighbor's aspin. Three puppies. Eyes Chico's food.",
    "portrait": "nami_portrait",
    "playable": false,
    "intro": "",
    "attributes": {}
  }
]
)GATEJSON";

inline constexpr char kGateRelationshipsJson[] = R"GATEJSON([
  { "from": "shadow", "to": "puppy", "kind": "hostile", "intensity": 3 },
  { "from": "puppy", "to": "shadow", "kind": "hostile", "intensity": 3 },
  { "from": "kali", "to": "itim", "kind": "hostile", "intensity": 2 },
  { "from": "itim", "to": "kali", "kind": "hostile", "intensity": 2 },
  { "from": "puppy", "to": "itim", "kind": "deferential", "intensity": 2 },
  { "from": "nami", "to": "chico", "kind": "food", "intensity": 2 },
  { "from": "chico", "to": "nami", "kind": "food", "intensity": 2 }
]
)GATEJSON";

inline constexpr char kGateChachaStoryJson[] = R"GATEJSON({
  "id": "chacha-door-open-01",
  "title": "The Door Is Open",
  "character": "chacha",
  "start": "start",
  "actors_default": ["chacha"],
  "nodes": {
    "start": {
      "text": "The door is open.\n\nNobody has noticed yet.\n\nChacha has noticed.",
      "art": "door_open",
      "actors": ["chacha"],
      "choices": [
        {
          "text": "RUN.",
          "next": "hallway",
          "effects": [
            { "op": "inc", "key": "char.chacha.confidence", "by": 1 },
            { "op": "dec", "key": "char.chacha.energy", "by": 1 },
            { "op": "set", "key": "flags.chacha_ran", "value": true },
            { "op": "push", "key": "world.recent_events", "value": "chacha_bolted" }
          ]
        },
        {
          "text": "Wait and listen.",
          "next": "listen",
          "effects": [
            { "op": "set", "key": "flags.chacha_waited", "value": true }
          ]
        },
        {
          "text": "Pretend not to notice.",
          "next": "pretend",
          "effects": [
            { "op": "dec", "key": "char.chacha.mood", "by": 1 }
          ]
        }
      ]
    },

    "listen": {
      "text": "Chacha freezes, one paw up. Ears swivel.\n\nSomewhere, a crate rattles.",
      "art": "listening",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "shadow_bark_early",
          "effects": [
            { "op": "set", "key": "flags.shadow_barking", "value": true },
            { "op": "push", "key": "world.recent_events", "value": "shadow_barked" }
          ],
          "text": "SHADOW starts up from his crate. BORK. BORK. BORK."
        }
      ],
      "choices": [
        {
          "text": "Okay. NOW run.",
          "next": "hallway",
          "effects": [
            { "op": "set", "key": "flags.chacha_ran", "value": true },
            { "op": "push", "key": "world.recent_events", "value": "chacha_bolted" }
          ]
        },
        {
          "text": "Stay put. This is clearly a trap.",
          "next": "end_cautious"
        }
      ]
    },

    "pretend": {
      "text": "Chacha studies the ceiling with great interest.\n\nThe door is still open. It is RIGHT THERE.",
      "art": "pretending",
      "actors": ["chacha"],
      "choices": [
        {
          "text": "...fine. RUN.",
          "next": "hallway",
          "effects": [
            { "op": "set", "key": "flags.chacha_ran", "value": true },
            { "op": "push", "key": "world.recent_events", "value": "chacha_bolted" }
          ]
        },
        {
          "text": "Commit to the nap.",
          "next": "end_nap"
        }
      ]
    },

    "hallway": {
      "text": "Chacha is a brown streak down the hallway.\n\nTiles, then grass, then open air.",
      "art": "hallway_blur",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "kali_follows",
          "effects": [
            { "op": "set", "key": "flags.kali_joined", "value": true }
          ],
          "text": "Kali sees the blur and gallops after her, delighted."
        },
        {
          "id": "shadow_barks",
          "when": [ { "key": "flags.shadow_barking", "op": "unset" } ],
          "effects": [
            { "op": "set", "key": "flags.shadow_barking", "value": true }
          ],
          "text": "Shadow barks at everyone about everything. BORK."
        }
      ],
      "choices": [
        {
          "text": "Straight for the gate.",
          "next": "gate",
          "effects": [ { "op": "set", "key": "flags.heading_gate", "value": true } ]
        },
        {
          "text": "Cut through the plants.",
          "next": "plants"
        }
      ]
    },

    "gate": {
      "text": "The gate. The big one.\n\nChacha skids to a halt before it, heart pounding.",
      "art": "the_gate",
      "actors": ["chacha", "kali"],
      "reactions": [
        {
          "id": "puppy_taunts_shadow",
          "when": [
            { "key": "flags.shadow_barking", "op": "set" },
            { "key": "rel.shadow.puppy", "op": "eq", "value": "hostile" }
          ],
          "effects": [ { "op": "set", "key": "flags.puppy_taunting", "value": true } ],
          "text": "Puppy trots to Shadow's crate just to gloat. Shadow loses it."
        },
        {
          "id": "nami_eyes_food",
          "effects": [ { "op": "set", "key": "flags.nami_near_food", "value": true } ],
          "text": "Nami drifts toward Chico's bowl. Chico's eyes narrow."
        },
        {
          "id": "leeg_retreats",
          "effects": [ { "op": "set", "key": "flags.leeg_hiding", "value": true } ],
          "text": "Leeg, long neck low, slinks behind the water drum."
        }
      ],
      "auto": "chaos"
    },

    "plants": {
      "text": "Chacha vanishes into the potted plants.\n\nLeaves rustle in a deeply suspicious way.",
      "art": "in_the_plants",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "chico_suspicious",
          "effects": [ { "op": "set", "key": "flags.chico_suspicious", "value": true } ],
          "text": "From the ledge, Chico watches the moving plants. He does not approve."
        }
      ],
      "auto": "chaos"
    },

    "chaos": {
      "text": "THE COMPOUND ERUPTS.",
      "art": "compound_erupts",
      "beat": true,
      "actors": ["chacha", "kali", "shadow", "puppy", "nami", "leeg"],
      "choices": [
        { "text": "Bolt through the gate!", "next": "outside" },
        { "text": "Freeze in the middle of it all.", "next": "end_frozen" }
      ]
    },

    "outside": {
      "text": "Chacha is OUTSIDE.\n\nThe street is enormous. A tricycle rumbles somewhere close.",
      "art": "outside_gate",
      "actors": ["chacha"],
      "reactions": [
        {
          "id": "regret_creeps_in",
          "text": "The confidence wavers. Everything is very, very big out here."
        }
      ],
      "choices": [
        {
          "text": "Keep going. This is MY adventure.",
          "next": "end_legend",
          "when": [ { "key": "char.chacha.confidence", "op": "gte", "value": 4 } ]
        },
        {
          "text": "...nope. Back inside. Immediately.",
          "next": "end_regret"
        }
      ]
    },

    "end_regret": {
      "text": "Chacha wheels around and rockets back through the gate.\n\nInside is good. Inside was always good.",
      "art": "home_safe",
      "ending": true,
      "ending_id": "regret"
    },

    "end_legend": {
      "text": "Chacha lifts her chin and struts down the street like she owns it.\n\nFor about nine glorious seconds, she does.",
      "art": "street_legend",
      "ending": true,
      "ending_id": "legend"
    },

    "end_cautious": {
      "text": "Chacha sits. Watches. Waits.\n\nThe door closes on its own. She knew it was a trap.",
      "art": "sitting_pretty",
      "ending": true,
      "ending_id": "cautious"
    },

    "end_nap": {
      "text": "Chacha curls up in a sunbeam.\n\nThe open door is a problem for a future, more energetic Chacha.",
      "art": "sunbeam_nap",
      "ending": true,
      "ending_id": "napped"
    },

    "end_frozen": {
      "text": "Chacha freezes at the center of the chaos.\n\nDogs orbit her. She has become the eye of the storm, and she is fine with this.",
      "art": "eye_of_storm",
      "ending": true,
      "ending_id": "frozen"
    }
  }
}
)GATEJSON";

}  // namespace gate_content
